-- CreateEnum
CREATE TYPE "EtapaProyecto" AS ENUM ('SIN_EJECUCION', 'EDTP_CONCLUIDO', 'EDTP_CONCLUIDO_ESPERA_INVERSION', 'EN_EJECUCION', 'EN_CIERRE', 'CONCLUIDO', 'CON_ENTREGA_DEFINITIVA', 'CONCILIACION_SALDOS', 'AUDITORIA_EXTERNA', 'SUSPENSION_CONTRATACION');

-- AlterTable
ALTER TABLE "Proyecto" ADD COLUMN     "detalleObs" TEXT,
ADD COLUMN     "estructuraFinanciamiento" TEXT,
ADD COLUMN     "modificaciones" TEXT,
ADD COLUMN     "montoEjecutado" DOUBLE PRECISION,
ADD COLUMN     "presupuestoVigente" DOUBLE PRECISION,
ADD COLUMN     "situacion" "EtapaProyecto",
ADD COLUMN     "tiempoEjecucion" TEXT,
ALTER COLUMN "contratoNro" DROP NOT NULL,
ALTER COLUMN "ordenProceder" DROP NOT NULL,
ALTER COLUMN "fechaConclusion" DROP NOT NULL,
ALTER COLUMN "direccion" DROP NOT NULL,
ALTER COLUMN "contratista" DROP NOT NULL,
ALTER COLUMN "supervisor" DROP NOT NULL,
ALTER COLUMN "fiscal" DROP NOT NULL;
